### ISSUE TITLE
`ERROR Render HTML failed: 2020/05/19/test/index.html

### ISSUE THREAD

**Issue by hi-dhl** [xCss/Valine#315]
请问一下这个是什么问题，刚才重新运行，就出现这个问题了, 已经执行过 clean ，还是不行

`ERROR Render HTML failed: 2020/05/19/test/index.html
TypeError: Cannot read property 'position' of null
    at find (/Users/denghuilong/Documents/project/github-owner/blog/themes/icarus/layout/common/widgets.jsx:24:53)
    at Array.find (<anonymous>)
    at hasColumn (/Users/denghuilong/Documents/project/github-owner/blog/themes/icarus/layout/common/widgets.jsx:24:31)
    at Function.getColumnCount (/Users/denghuilong/Documents/project/github-owner/blog/themes/icarus/layout/common/widgets.jsx:30:13)
    at _class.render (/Users/denghuilong/Documents/project/github-owner/blog/themes/icarus/layout/layout.jsx:15:37)
    at renderVNodeToString (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/inferno-server/dist/index.cjs.js:206:41)
    at renderToString (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/inferno-server/dist/index.cjs.js:352:12)
    at /Users/denghuilong/Documents/project/github-owner/blog/node_modules/hexo-renderer-inferno/lib/compile.js:35:46
    at viewFn._compiled (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/hexo/lib/theme/view.js:41:15)
    at /Users/denghuilong/Documents/project/github-owner/blog/node_modules/hexo/lib/theme/view.js:52:23
    at tryCatcher (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/denghuilong/Documents/project/github-owner/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)`

**Comment by hi-dhl** [comment]
已经解决
