### ISSUE TITLE
Array原型被污染导致渲染失败

### ISSUE THREAD

**Issue by sumy7** [xCss/Valine#358]
版本 v1.4.14

启动报错
```
Valine.min.js:formatted:2866 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.vfunction(){this.length=0}' is not a valid selector.
    at r (http://unpkg.com/valine/dist/Valine.min.js:12:36952)
    at Array.find (http://unpkg.com/valine/dist/Valine.min.js:7:2301)
    at http://unpkg.com/valine/dist/Valine.min.js:12:19878
    at o.bind (http://unpkg.com/valine/dist/Valine.min.js:12:20016)
    at http://unpkg.com/valine/dist/Valine.min.js:12:12032
    at http://unpkg.com/valine/dist/Valine.min.js:12:23934
    at Function.sdkLoader (http://unpkg.com/valine/dist/Valine.min.js:7:4990)
    at http://unpkg.com/valine/dist/Valine.min.js:7:5059
    at HTMLScriptElement.n.onload.n.onreadystatechange (http://unpkg.com/valine/dist/Valine.min.js:7:4779)
```

经排查是项目中同时引入了Swiftype站内搜索，st.js库在Array原型中添加了一些方法，导致遍历失败。
以下位置for循环遍历的时候，由于Array原型被污染，导致遍历出来很多不需要的属性。
```javascript
            !function(t) {
                if (t = y.default.store.get(h.MetaCacheKey) || t)
                    for (var n in p) {
                        var r = p[n];
                        e.$el.find(".v" + r).val(y.default.unescape(t[r])),
                        E[r] = t[r]
                    }
                var o = y.default.store.get(h.QQCacheKey);
                E.QQAvatar = e.config.enableQQ && !!o && o.pic || ""
            }(),
```

测试代码

```
for (let n in p) {console.log(n)}
0
1
2
clear
first
last
flatten
each
include
```

建议通过 `hasOwnProperty` 将原型中的属性过滤掉。

**Comment by xCss** [comment]
收到，感谢反馈，将在下个版本修复 ～

**Comment by sumy7** [comment]
下版本发布时，还请告知一下。
在此期间，就先暂时把Swiftype功能禁用了（反正也没什么人用）。
